import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { AssessmentState, Framework, FrameworkScore, STATUS_LABEL, ControlStatus } from "./types";

const NAVY = "#0A1128";
const NAVY2 = "#0F172A";
const EMERALD = "#10B981";
const CYAN = "#06B6D4";
const AMBER = "#F59E0B";
const ROSE = "#F43F5E";
const VIOLET = "#7C3AED";
const SLATE = "#64748B";

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

function statusColor(status: ControlStatus): string {
  switch (status) {
    case "covered":
      return EMERALD;
    case "partial":
      return AMBER;
    case "gap":
      return ROSE;
    case "na":
      return SLATE;
    default:
      return NAVY2;
  }
}

function priorityLabel(priority?: string): string {
  switch (priority) {
    case "critical":
      return "Critical";
    case "high":
      return "High";
    case "medium":
      return "Medium";
    case "low":
      return "Low";
    default:
      return "—";
  }
}

function priorityColor(priority?: string): string {
  switch (priority) {
    case "critical":
      return ROSE;
    case "high":
      return AMBER;
    case "medium":
      return CYAN;
    case "low":
      return SLATE;
    default:
      return SLATE;
  }
}

export function generateGapAssessmentPdf(
  framework: Framework,
  score: FrameworkScore,
  state: AssessmentState
) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;

  // ---- Cover page ----
  const [nr, ng, nb] = hexToRgb(NAVY);
  doc.setFillColor(nr, ng, nb);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text("ComplyCheck", margin, 110);
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("Compliance Readiness & Gap Assessment Report", margin, 134);

  doc.setDrawColor(...hexToRgb(EMERALD));
  doc.setLineWidth(2);
  doc.line(margin, 150, pageWidth - margin, 150);

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(framework.name, margin, 200);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const meta: [string, string][] = [
    ["Company", state.meta.companyName || "—"],
    ["Assessor Role", state.meta.assessorRole || "—"],
    ["Report Date", new Date().toLocaleDateString()],
    ["Framework Version", framework.version],
    ["Overall Readiness", `${score.readinessPct}%`],
    ["Risk Level", score.riskLevel],
  ];
  let y = 230;
  for (const [label, value] of meta) {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, margin + 140, y);
    y += 20;
  }

  doc.setFontSize(9);
  doc.setTextColor(200, 210, 230);
  doc.text(
    "Generated by ComplyCheck — for questions or collaboration, contact trycomplycheck@gmail.com",
    margin,
    pageHeight - 40
  );

  // ---- Executive summary page ----
  doc.addPage();
  doc.setTextColor(20, 20, 30);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Executive Summary", margin, 60);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const summaryText = `This assessment covers ${score.total} controls across ${framework.domains.length} domains/categories. Overall readiness is ${score.readinessPct}%, with a gap ratio of ${score.gapPct}%. Assessed risk level: ${score.riskLevel}. Coverage breakdown: ${score.covered} fully covered, ${score.partial} partial, ${score.gap} gaps, ${score.na} N/A, ${score.unmarked} unmarked.`;
  doc.text(summaryText, margin, 82, { maxWidth: pageWidth - margin * 2 });

  autoTable(doc, {
    startY: 110,
    head: [["Status", "Count", "% of assessed"]],
    body: [
      ["Covered", String(score.covered), `${Math.round((score.covered / Math.max(score.total, 1)) * 100)}%`],
      ["Partial", String(score.partial), `${Math.round((score.partial / Math.max(score.total, 1)) * 100)}%`],
      ["Gap", String(score.gap), `${Math.round((score.gap / Math.max(score.total, 1)) * 100)}%`],
      ["N/A", String(score.na), `${Math.round((score.na / Math.max(score.total, 1)) * 100)}%`],
      ["Unmarked", String(score.unmarked), `${Math.round((score.unmarked / Math.max(score.total, 1)) * 100)}%`],
    ],
    theme: "grid",
    headStyles: { fillColor: hexToRgb(NAVY2) },
    styles: { fontSize: 9 },
    margin: { left: margin, right: margin },
  });

  // ---- Domain breakdown ----
  const afterSummaryY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 30;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Domain-by-Domain Breakdown", margin, afterSummaryY);

  autoTable(doc, {
    startY: afterSummaryY + 12,
    head: [["Domain", "Covered", "Partial", "Gap", "N/A", "Readiness %"]],
    body: score.domainScores.map((d) => [
      d.domainName,
      String(d.covered),
      String(d.partial),
      String(d.gap),
      String(d.na),
      `${d.readinessPct}%`,
    ]),
    theme: "striped",
    headStyles: { fillColor: hexToRgb(NAVY2) },
    styles: { fontSize: 8 },
    margin: { left: margin, right: margin },
  });

  // ---- Prioritized Gap Analysis with Remediation Strategies ----
  doc.addPage();
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 20, 30);
  doc.text("Prioritized Gap Analysis & Remediation Strategies", margin, 60);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(
    "The following gaps and partial implementations are prioritized by risk and remediation impact. Use this as a roadmap.",
    margin,
    78,
    { maxWidth: pageWidth - margin * 2 }
  );

  const gapControls = framework.controls.filter((c) => {
    const status = state.controlAssessments[c.id]?.status ?? "unmarked";
    return status === "gap" || status === "partial";
  }).sort((a, b) => {
    const order: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
    return (order[a.priority ?? "low"] ?? 3) - (order[b.priority ?? "low"] ?? 3);
  });

  if (gapControls.length > 0) {
    autoTable(doc, {
      startY: 96,
      head: [["Priority", "Ref", "Control", "Status", "Remediation Strategy"]],
      body: gapControls.map((c) => {
        const status = state.controlAssessments[c.id]?.status ?? "unmarked";
        return [
          priorityLabel(c.priority),
          c.ref,
          c.title,
          STATUS_LABEL[status],
          c.remediationStrategy || c.implementationGuide,
        ];
      }),
      theme: "grid",
      headStyles: { fillColor: hexToRgb(ROSE) },
      styles: { fontSize: 7, cellWidth: "wrap", overflow: "linebreak", minCellHeight: 30 },
      columnStyles: {
        0: { cellWidth: 50, fontStyle: "bold" },
        1: { cellWidth: 55 },
        2: { cellWidth: 130 },
        3: { cellWidth: 55 },
        4: { cellWidth: "auto" },
      },
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 0) {
          const c = gapControls[data.row.index];
          (data.cell.styles as { textColor: [number, number, number] }).textColor = hexToRgb(priorityColor(c.priority));
        }
        if (data.section === "body" && data.column.index === 3) {
          const c = gapControls[data.row.index];
          const status = state.controlAssessments[c.id]?.status ?? "unmarked";
          (data.cell.styles as { textColor: [number, number, number]; fontStyle: string }).textColor = hexToRgb(statusColor(status));
          (data.cell.styles as { fontStyle: string }).fontStyle = "bold";
        }
      },
      margin: { left: margin, right: margin },
    });
  } else {
    doc.setFontSize(10);
    doc.text("No gaps or partial controls identified.", margin, 100);
  }

  // ---- Remediation Roadmap by Domain ----
  doc.addPage();
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Remediation Roadmap by Domain", margin, 60);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(
    "Group gaps by domain for sequenced remediation planning. Prioritize Critical/High items first; aim for quick wins within 30 days.",
    margin,
    78,
    { maxWidth: pageWidth - margin * 2 }
  );

  const roadmapData: { domain: string; rows: { ref: string; control: string; status: string; priority: string; remediation: string }[] }[] = [];
  for (const domain of framework.domains) {
    const rows = gapControls
      .filter((c) => c.domainId === domain.id)
      .map((c) => ({
        ref: c.ref,
        control: c.title,
        status: STATUS_LABEL[state.controlAssessments[c.id]?.status ?? "unmarked"],
        priority: priorityLabel(c.priority),
        remediation: c.remediationStrategy || c.implementationGuide,
      }));
    if (rows.length > 0) {
      roadmapData.push({ domain: domain.name, rows });
    }
  }

  let startY = 96;
  for (const group of roadmapData) {
    if (startY > pageHeight - 100) {
      doc.addPage();
      startY = margin;
    }
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20, 20, 30);
    doc.text(group.domain, margin, startY);
    startY += 6;

    autoTable(doc, {
      startY: startY + 4,
      head: [["Ref", "Control", "Status", "Priority", "Remediation"]],
      body: group.rows.map((r) => [r.ref, r.control, r.status, r.priority, r.remediation]),
      theme: "striped",
      headStyles: { fillColor: hexToRgb(VIOLET) },
      styles: { fontSize: 7, cellWidth: "wrap", overflow: "linebreak", minCellHeight: 26 },
      columnStyles: {
        0: { cellWidth: 50 },
        1: { cellWidth: 130 },
        2: { cellWidth: 50 },
        3: { cellWidth: 45 },
        4: { cellWidth: "auto" },
      },
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 3) {
          const r = group.rows[data.row.index];
          const priorityMap: Record<string, string> = { Critical: ROSE, High: AMBER, Medium: CYAN, Low: SLATE };
          (data.cell.styles as { textColor: [number, number, number]; fontStyle: string }).textColor = hexToRgb(priorityMap[r.priority] ?? SLATE);
          (data.cell.styles as { fontStyle: string }).fontStyle = "bold";
        }
      },
      margin: { left: margin, right: margin },
    });
    startY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 16;
  }

  // ---- Policy status ----
  doc.addPage();
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 20, 30);
  doc.text("Policy Requirements Status", margin, 60);

  const relevantPolicyIds = new Set(framework.controls.flatMap((c) => c.relatedPolicies));
  autoTable(doc, {
    startY: 80,
    head: [["Policy", "Status"]],
    body: Array.from(relevantPolicyIds).map((pid) => [
      pid,
      STATUS_LABEL[state.policyAssessments[pid]?.status ?? "unmarked"],
    ]),
    theme: "striped",
    headStyles: { fillColor: hexToRgb(NAVY2) },
    styles: { fontSize: 9 },
    margin: { left: margin, right: margin },
  });

  // ---- Recommended next steps ----
  const afterPolicyY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 30;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Recommended Next Steps", margin, afterPolicyY);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const nextSteps = [
    "1. Triage Critical and High priority gaps with leadership and assign owners within 7 days.",
    "2. Schedule weekly remediation stand-ups to track progress against SLA.",
    "3. For partially implemented controls, document residual gaps and remediation plan.",
    "4. Re-run this assessment monthly to track readiness improvement.",
    "5. Export the JSON or CSV for integration into your GRC platform or ticketing system.",
  ];
  let stepY = afterPolicyY + 16;
  for (const step of nextSteps) {
    doc.text(step, margin, stepY, { maxWidth: pageWidth - margin * 2 });
    stepY += 18;
  }

  void CYAN;
  void AMBER;

  doc.save(`${framework.shortName.replace(/\s+/g, "_")}_Gap_Assessment_Report.pdf`);
}
